# Generated by Django 5.0.6 on 2024-06-21 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='modified_on',
        ),
    ]
